name: Snyk Scan
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go to dependency directory
        run: cp apiREST/requirements.txt .
      - name: LS
        run: ls
      - name: pip install
        run: pip install -r requirements.txt
      - name: Run Snyk to check vulnerabilities in python code
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high   -d       
      
